services:
  yt-cipher:
    build: ./infra/yt-cipher
    restart: unless-stopped
    environment:
      - API_TOKEN=musry_cipher_secret
      - OVERRIDE_PLAYER_VARIANT=IAS

  lavalink:
    build:
      context: .
      dockerfile: infra/lavalink/Dockerfile
    restart: unless-stopped
    ports:
      - '2333:2333'
    volumes:
      - ./infra/lavalink/application.yml:/opt/Lavalink/application.yml
    environment:
      - LAVALINK_YOUTUBE_OAUTH_TOKEN=${LAVALINK_YOUTUBE_OAUTH_TOKEN}
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - SOUNDCLOUD_CLIENT_ID=${SOUNDCLOUD_CLIENT_ID}
      - SOUNDCLOUD_OAUTH_TOKEN=${SOUNDCLOUD_OAUTH_TOKEN}
    depends_on:
      - yt-cipher

  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
      - LAVALINK_SECURE=false
    volumes:
      - ./apps/bot/src:/app/apps/bot/src
    depends_on:
      - lavalink
